import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "sercha-enterprise-api",
    },
    {
      type: "category",
      label: "Audit",
      items: [
        {
          type: "doc",
          id: "list-ingestion-audit-events",
          label: "List ingestion audit events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-ingestion-audit-event-by-id",
          label: "Get ingestion audit event by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-retrieval-audit-events",
          label: "List retrieval audit events",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-retrieval-audit-event-by-id",
          label: "Get retrieval audit event by ID",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      items: [
        {
          type: "doc",
          id: "list-job-history",
          label: "List job history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-job-details",
          label: "Get job details",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-job-statistics",
          label: "Get job statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-upcoming-jobs",
          label: "Get upcoming jobs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "trigger-reindex",
          label: "Trigger reindex",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-search-analytics",
          label: "Get search analytics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-search-history",
          label: "Get search history",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-search-metrics",
          label: "Get search metrics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-admin-statistics",
          label: "Get admin statistics",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      items: [
        {
          type: "doc",
          id: "user-login",
          label: "User login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "logout-user",
          label: "Logout user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "refresh-token",
          label: "Refresh token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Bindings",
      items: [
        {
          type: "doc",
          id: "list-bindings-flat",
          label: "List bindings (flat)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-binding",
          label: "Create a binding",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-binding",
          label: "Delete a binding",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-binding",
          label: "Get a binding",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "preview-extraction-dag",
          label: "Preview extraction DAG",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-binding-hints",
          label: "List binding hints",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "set-per-invocation-hint",
          label: "Set per-invocation hint",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "clear-per-invocation-hint",
          label: "Clear per-invocation hint",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "rebind-to-ontology-version",
          label: "Rebind to ontology version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "trigger-a-binding-run",
          label: "Trigger a binding run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-binding-runs",
          label: "List binding runs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-bindings-by-corpus",
          label: "List bindings by corpus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-bindings-by-ontology",
          label: "List bindings by ontology",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Capabilities",
      items: [
        {
          type: "doc",
          id: "get-capabilities",
          label: "Get capabilities",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-capability-preferences",
          label: "Get capability preferences",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-capability-preferences",
          label: "Update capability preferences",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "Connections",
      items: [
        {
          type: "doc",
          id: "list-connections",
          label: "List connections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-connection",
          label: "Create connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-connection",
          label: "Delete connection",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-connection",
          label: "Get connection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-containers",
          label: "List containers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-connection-sources",
          label: "Get connection sources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "test-connection",
          label: "Test connection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "microsoft-admin-consent-callback",
          label: "Microsoft admin-consent callback",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-microsoft-admin-consent-url",
          label: "Get Microsoft admin-consent URL",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Corpuses",
      items: [
        {
          type: "doc",
          id: "list-corpora",
          label: "List corpora",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-corpus",
          label: "Create a corpus",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-corpus",
          label: "Delete a corpus",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-corpus",
          label: "Get a corpus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-a-corpus",
          label: "Update a corpus",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "claim-a-chain-inside-an-authorised-subtree",
          label: "Claim a chain inside an authorised subtree",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "add-a-container-to-a-corpus",
          label: "Add a container to a corpus",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "remove-a-container-from-a-corpus",
          label: "Remove a container from a corpus",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Pipelines",
      items: [
        {
          type: "doc",
          id: "list-search-pipelines-by-corpus",
          label: "List search pipelines by corpus",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-search-pipeline-by-corpus-and-name",
          label: "Get a search pipeline by corpus and name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-pipelines",
          label: "List pipelines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-pipeline",
          label: "Create a pipeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-a-pipeline",
          label: "Get a pipeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "publish-a-new-pipeline-version",
          label: "Publish a new pipeline version",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "dry-run-a-candidate-pipeline-dag",
          label: "Dry-run a candidate pipeline DAG",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "trigger-a-pipeline-run",
          label: "Trigger a pipeline run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "set-pipeline-schedule",
          label: "Set pipeline schedule",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "list-pipeline-versions",
          label: "List pipeline versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-pipeline-version",
          label: "Get a pipeline version",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "restore-a-pipeline-version",
          label: "Restore a pipeline version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "diff-two-pipeline-versions",
          label: "Diff two pipeline versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-search-pipelines",
          label: "List search pipelines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-search-pipeline",
          label: "Create a search pipeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-search-pipeline",
          label: "Delete a search pipeline",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-search-pipeline",
          label: "Get a search pipeline",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Documents",
      items: [
        {
          type: "doc",
          id: "delete-document",
          label: "Delete document",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-document",
          label: "Get document",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "open-document",
          label: "Open document",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Graphs",
      items: [
        {
          type: "doc",
          id: "delete-an-edge",
          label: "Delete an edge",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-an-edge",
          label: "Get an edge",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-graphs",
          label: "List graphs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-graph",
          label: "Get a graph",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-or-update-a-graph",
          label: "Create or update a graph",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "list-edges-in-a-graph",
          label: "List edges in a graph",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-nodes-in-a-graph",
          label: "List nodes in a graph",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-a-node",
          label: "Get a node",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-node-neighbours",
          label: "Get node neighbours",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-graph-statistics",
          label: "Get graph statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-a-node",
          label: "Delete a node",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-node-any-graph",
          label: "Get a node (any graph)",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Ontologies",
      items: [
        {
          type: "doc",
          id: "delete-a-relationship-declaration",
          label: "Delete a relationship declaration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-relationship-declaration",
          label: "Get a relationship declaration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-entity-collections",
          label: "List entity collections",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-an-entity-collection",
          label: "Create an entity collection",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-an-entity-collection",
          label: "Delete an entity collection",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-an-entity-collection",
          label: "Get an entity collection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-an-entity-collection",
          label: "Update an entity collection",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "list-relationships-from-a-collection",
          label: "List relationships from a collection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-relationship-declaration",
          label: "Create a relationship declaration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-ontology-entities-in-a-collection",
          label: "List ontology entities in a collection",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-an-ontology-entity-type",
          label: "Create an ontology entity type",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-an-ontology-entity-type",
          label: "Delete an ontology entity type",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-an-ontology-entity-type",
          label: "Get an ontology entity type",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-an-ontology-entity-type",
          label: "Update an ontology entity type",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "list-ontology-versions",
          label: "List ontology versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-ontology-version-by-number",
          label: "Get ontology version by number",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "freeze-ontology-version",
          label: "Freeze ontology version",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Grants",
      items: [
        {
          type: "doc",
          id: "list-grants",
          label: "List grants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-grant",
          label: "Create a grant",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-grant",
          label: "Delete a grant",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-grant",
          label: "Get a grant",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "check-grant",
          label: "Check grant",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Groups",
      items: [
        {
          type: "doc",
          id: "list-groups",
          label: "List groups",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-group",
          label: "Create a group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-group",
          label: "Delete a group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-group",
          label: "Get a group",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-group-members",
          label: "List group members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "add-member-to-group",
          label: "Add member to group",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "remove-member-from-group",
          label: "Remove member from group",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "list-groups-for-user",
          label: "List groups for user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Health",
      items: [
        {
          type: "doc",
          id: "health-check",
          label: "Health check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "readiness-check",
          label: "Readiness check",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-api-version",
          label: "Get API version",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Lineage",
      items: [
        {
          type: "doc",
          id: "get-lineage-view-for-a-node",
          label: "Get lineage view for a node",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "get-current-user",
          label: "Get current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-all-users",
          label: "List all users",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-user",
          label: "Create user",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-user",
          label: "Delete user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-user",
          label: "Get user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-user",
          label: "Update user",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "reset-user-password",
          label: "Reset user password",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "OAuth",
      items: [
        {
          type: "doc",
          id: "start-o-auth-authorization",
          label: "Start OAuth authorization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "o-auth-callback",
          label: "OAuth callback",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Ops",
      items: [
        {
          type: "doc",
          id: "list-registered-ops",
          label: "List registered ops",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Runs",
      items: [
        {
          type: "doc",
          id: "list-runs-for-a-pipeline",
          label: "List runs for a pipeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-runs-across-all-pipelines",
          label: "List runs across all pipelines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "delete-a-run",
          label: "Delete a run",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-run",
          label: "Get a run",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "cancel-a-run",
          label: "Cancel a run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-graph-produced-by-a-run",
          label: "Delete graph produced by a run",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "list-nodes-created-by-a-run",
          label: "List nodes created by a run",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "replay-a-run",
          label: "Replay a run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-run-staging-delta",
          label: "Get run staging delta",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-run-trace",
          label: "Get run trace",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Plugins",
      items: [
        {
          type: "doc",
          id: "list-installed-plugins",
          label: "List installed plugins",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "register-a-plugin-provider",
          label: "Register a plugin provider",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-plugin-provider",
          label: "Delete a plugin provider",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-plugin-provider",
          label: "Get a plugin provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-a-plugin-provider",
          label: "Update a plugin provider",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "test-plugin-connectivity",
          label: "Test plugin connectivity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "register-plugin-from-manifest-url",
          label: "Register plugin from manifest URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-plugin-library",
          label: "List plugin library",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Providers",
      items: [
        {
          type: "doc",
          id: "list-providers",
          label: "List providers",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "SerchaQL",
      items: [
        {
          type: "doc",
          id: "execute-a-sercha-ql-statement",
          label: "Execute a SerchaQL statement",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "execute-a-sercha-ql-json-ir-query",
          label: "Execute a SerchaQL JSON IR query",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Search",
      items: [
        {
          type: "doc",
          id: "search-documents",
          label: "Search documents",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "search-by-document",
          label: "Search by document",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Settings",
      items: [
        {
          type: "doc",
          id: "get-settings",
          label: "Get settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-settings",
          label: "Update settings",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "AI Settings",
      items: [
        {
          type: "doc",
          id: "get-ai-settings",
          label: "Get AI settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-ai-settings",
          label: "Update AI settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "get-ai-providers",
          label: "Get AI providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-ai-status",
          label: "Get AI status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "test-ai-connection",
          label: "Test AI connection",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Setup",
      items: [
        {
          type: "doc",
          id: "initial-setup",
          label: "Initial setup",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "get-setup-status",
          label: "Get setup status",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sources",
      items: [
        {
          type: "doc",
          id: "list-sources",
          label: "List sources",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-source",
          label: "Create source",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-source",
          label: "Delete source",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-source",
          label: "Get source",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-source",
          label: "Update source",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "update-source-containers",
          label: "Update source containers",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "disable-source",
          label: "Disable source",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-source-documents",
          label: "List source documents",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "enable-source",
          label: "Enable source",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-failing-documents-for-a-source",
          label: "List failing documents for a source",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "get-sync-state-for-source",
          label: "Get sync state for source",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "trigger-sync",
          label: "Trigger sync",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-source-containers",
          label: "List source containers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "purge-a-container-subtree",
          label: "Purge a container subtree",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "authorise-a-container-chain",
          label: "Authorise a container chain",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-authorised-source-containers",
          label: "List authorised source containers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "list-claimed-source-containers",
          label: "List claimed source containers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "unauthorise-containers",
          label: "Unauthorise containers",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "list-sync-states",
          label: "List sync states",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Sync",
      items: [
        {
          type: "doc",
          id: "cancel-a-sync",
          label: "Cancel a sync",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Studio",
      items: [
        {
          type: "doc",
          id: "list-studio-worksheets",
          label: "List studio worksheets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "create-a-studio-worksheet",
          label: "Create a studio worksheet",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "delete-a-studio-worksheet",
          label: "Delete a studio worksheet",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "get-a-studio-worksheet",
          label: "Get a studio worksheet",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "update-a-studio-worksheet",
          label: "Update a studio worksheet",
          className: "api-method put",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
